# Generated by Django 4.2.4 on 2023-09-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.label')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.lead')),
            ],
        ),
    ]
