# Generated by Django 4.2.4 on 2023-09-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.activityname'),
        ),
    ]
