# Generated by Django 4.2.4 on 2023-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_clientip_lead_location_lead_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
