# Generated by Django 4.2.4 on 2023-09-22 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_activity_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
